<a href="https://colab.research.google.com/github/rafzieli/daca-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

In [2]:
import numpy as np
np.__version__

'1.21.5'

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

1D Array

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [12]:
x = np.array([1.3, 1.4, 1.6])
print(x)

[1.3 1.4 1.6]


2D Array

In [13]:
x = np.array([[1, 3], [-1, 5]])
x

array([[ 1,  3],
       [-1,  5]])

In [14]:
x.ndim

2

In [15]:
x.shape

(2, 2)

In [16]:
x = np.array([[1, 2, 4], [1, 3, 5]])
x

array([[1, 2, 4],
       [1, 3, 5]])

3D Array

In [17]:
x = np.array(
    [[[4, 5, 2],
     [2, 4, 5]],

    [[4, 6, 4],
     [3, 5, 4]],
     
     [[4, 6, 4],
     [3, 5, 4]]]

)
x

array([[[4, 5, 2],
        [2, 4, 5]],

       [[4, 6, 4],
        [3, 5, 4]],

       [[4, 6, 4],
        [3, 5, 4]]])

In [18]:
x.ndim

3

In [19]:
x.shape

(3, 2, 3)

### <a name='a2'></a> Typy danych

In [20]:
A = np.array([1, 2, 4])
A.dtype

dtype('int64')

In [21]:
A = np.array([1.0, 2.4, 4])
A.dtype

dtype('float64')

In [22]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [23]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [24]:
A = np.array([1.0, 2.4, 4], dtype = 'int')
A.dtype

dtype('int64')

In [25]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [26]:
A = np.array([12,120, 230], dtype = np.int8) # do zdjec
A.dtype

dtype('int8')

### <a name='a3'></a> Tworzenie tablic

In [27]:
np.zeros(shape = (4, 10), dtype='int') # domyslnie float

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
np.ones(shape = (5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.full(shape = (3, 3), fill_value=4, dtype = 'int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(start =5, stop=10)

array([5, 6, 7, 8, 9])

In [32]:
np.arange(start =10, stop=100, step = 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
np.arange(start =100, stop=10, step = -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [34]:
np.arange(start = 0, stop = 1, step = 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [35]:
np.linspace(start = 0, stop = 1, num=34)

array([0.        , 0.03030303, 0.06060606, 0.09090909, 0.12121212,
       0.15151515, 0.18181818, 0.21212121, 0.24242424, 0.27272727,
       0.3030303 , 0.33333333, 0.36363636, 0.39393939, 0.42424242,
       0.45454545, 0.48484848, 0.51515152, 0.54545455, 0.57575758,
       0.60606061, 0.63636364, 0.66666667, 0.6969697 , 0.72727273,
       0.75757576, 0.78787879, 0.81818182, 0.84848485, 0.87878788,
       0.90909091, 0.93939394, 0.96969697, 1.        ])

In [36]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
A.reshape((3, -1)) # chcemy miec 3 wiersze, podajac -1 chcemy aby python sam nam dobral odpowiednia ilosc kolumn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
A.reshape((-1, 3)) # odwrotnie jak powyzej

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [105]:
A = np.array([3, 2, 1, 3])
B = np.array([3,-2, 3, 4])

In [41]:
A + B

array([6, 0, 4, 7])

In [42]:
A - B

array([ 0,  4, -2, -1])

In [43]:
A * B

array([ 9, -4,  3, 12])

In [44]:
A / B

array([ 1.        , -1.        ,  0.33333333,  0.75      ])

In [45]:
A + 3

array([6, 5, 4, 6])

In [46]:
2 * B

array([ 6, -4,  6,  8])

In [47]:
np.add(A, B)

array([6, 0, 4, 7])

In [106]:
np.subtract(A, B)

array([ 0,  4, -2, -1])

In [107]:
np.multiply(A, B)

array([ 9, -4,  3, 12])

In [108]:
np.divide(A, B)

array([ 1.        , -1.        ,  0.33333333,  0.75      ])

In [113]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X)
print()
print(Y)

[[ 1  3]
 [-2  0]]

[[ 6  0]
 [-1  2]]


In [111]:
X * Y

array([[6, 0],
       [2, 0]])

In [114]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [115]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [116]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [117]:
X @ Y

array([[  3,   6],
       [-12,   0]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [48]:
np.random.seed(0)

In [49]:
np.random.randn()

1.764052345967664

In [50]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [51]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [52]:
np.random.rand()

0.1965823616800535

In [53]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [54]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [55]:
np.random.randint(10)

3

In [56]:
np.random.randint(low=10, high=101)

56

In [57]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [58]:
np.random.choice([4, 2, 1, 3, 5])

4

In [59]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [60]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.random.shuffle(data)

In [62]:
data

array([6, 9, 1, 5, 0, 7, 3, 4, 8, 2])

### <a name='a6'></a> Podstawowe funkcje

In [63]:
np.exp(1)

2.718281828459045

In [64]:
np.sqrt(9)

3.0

In [65]:
np.all([2, 3, 1])

True

In [66]:
np.any([0, 0, 0])

False

In [67]:
bool(1.3)

True

In [68]:
A = np.random.rand(5)
A

array([0.29743695, 0.81379782, 0.39650574, 0.8811032 , 0.58127287])

In [69]:
np.argmax(A)

3

In [70]:
A[np.argmax(A)]

0.8811031971111616

In [71]:
np.argmin(A)

0

In [72]:
np.argsort(A)

array([0, 2, 4, 1, 3])

In [73]:
np.max(A)

0.8811031971111616

In [74]:
np.min(A)

0.29743695085513366

In [75]:
np.mean(A)

0.5940233162303231

In [76]:
np.median(A)

0.5812728726358587

In [77]:
np.std(A)

0.2270924608641256

###  <a name='a7'></a> Indeksowanie, Wycinanie

In [78]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [80]:
A[2]

2

In [81]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [82]:
A[:2]

array([0, 1])

In [83]:
A[[0, 2]]

array([0, 2])

In [84]:
A[-1]

19

In [85]:
A[10:15]

array([10, 11, 12, 13, 14])

In [86]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [88]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [89]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [91]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [92]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [93]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
A.shape

(4, 5)

In [95]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [96]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [97]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [98]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [99]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [100]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [101]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [102]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])